apiVersion: v1
kind: Namespace
metadata:
  name: monitor-system-dev
  labels:
    name: monitor-system-dev
    environment: development
    app.kubernetes.io/name: monitor-system
    app.kubernetes.io/version: "dev"