package cn.flying.service.manifest.backfill;

/**
 * Machine-readable evidence, retry, and administrative reason catalog.
 */
public enum ManifestBackfillReason {
    BACKFILLABLE_EVIDENCE,
    ALREADY_MANIFEST,
    FILE_NOT_SUCCESS,
    FILE_DELETED,
    VERSION_UNSTABLE,
    SHARE_SOURCE_UNPROVEN,
    MISSING_POINTER,
    MALFORMED_POINTER,
    LEGACY_ORDER_UNTRUSTED,
    MISSING_SIZE,
    MISSING_PLAIN_HASH,
    DUPLICATE_INDEX,
    GAPPED_INDEX,
    CROSS_TENANT_PATH,
    UNKNOWN_ENCRYPTION_FORMAT,
    OBJECT_NOT_FOUND,
    OBJECT_HEAD_MISMATCH,
    AGGREGATE_SIZE_MISMATCH,
    CONTENT_HASH_MISMATCH,
    CHAIN_RPC_TRANSIENT,
    STORAGE_RPC_TRANSIENT,
    DATABASE_TRANSIENT,
    DUPLICATE_ACTIVE_MANIFEST,
    ACTIVE_MANIFEST_INVALID,
    EVIDENCE_DIGEST_CHANGED,
    CLAIM_LOST,
    MANUAL_REVIEW,
    ADMIN_REQUEUED,
    MAX_ATTEMPTS_EXHAUSTED,
    UNKNOWN_REFERENCE,
    REFERENCE_ADDED,
    PROTECTION_PERIOD_ACTIVE,
    DELETE_HEAD_MISMATCH,
    DELETE_RPC_TRANSIENT,
    LEGACY_DOWNLOAD_ALLOWED
}
