server:
  port: 8084

spring:
  application:
    name: monitor-websocket-service
    
  redis:
    host: localhost
    port: 6379
    database: 4
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 10s
      influx:
        enabled: false
    distribution:
      percentiles-histogram:
        http.server.requests: true
        monitor.method.execution.time: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        monitor.method.execution.time: 0.5, 0.95, 0.99
    tags:
      application: monitor-websocket-service
      service: websocket-service
  tracing:
    enabled: true
    sampling:
      probability: 0.1
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    cn.flying.monitor: DEBUG