-- H2 schema for platform-identity integration tests
-- 生成核心表结构以支撑 OAuth/SSO 流程、批量撤销与网关限流测试

DROP TABLE IF EXISTS traffic_monitor;
DROP TABLE IF EXISTS token_monitor;
DROP TABLE IF EXISTS user_session;
DROP TABLE IF EXISTS third_party_account;
DROP TABLE IF EXISTS oauth_code;
DROP TABLE IF EXISTS oauth_client;
DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS account;

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(128) NOT NULL,
    email VARCHAR(100) NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    avatar VARCHAR(255),
    register_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    CONSTRAINT uk_account_username UNIQUE (username),
    CONSTRAINT uk_account_email UNIQUE (email)
);

CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(100),
    user_role VARCHAR(20),
    module VARCHAR(50),
    operation_type VARCHAR(50),
    description VARCHAR(500),
    request_url VARCHAR(500),
    request_method VARCHAR(10),
    request_param CLOB,
    response_result CLOB,
    client_ip VARCHAR(50),
    user_agent VARCHAR(1000),
    class_name VARCHAR(200),
    method_name VARCHAR(100),
    status TINYINT DEFAULT 0,
    error_msg CLOB,
    execution_time BIGINT,
    risk_level VARCHAR(20),
    operation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE oauth_client (
    client_id BIGINT PRIMARY KEY,
    client_key VARCHAR(100) NOT NULL,
    client_secret VARCHAR(255) NOT NULL,
    client_name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    redirect_uris VARCHAR(1000),
    scopes VARCHAR(500),
    grant_types VARCHAR(200),
    access_token_validity INT,
    refresh_token_validity INT,
    auto_approve TINYINT,
    status TINYINT,
    logo_url VARCHAR(255),
    website_url VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0
);
CREATE UNIQUE INDEX uk_oauth_client_key ON oauth_client(client_key);

CREATE TABLE oauth_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    client_key VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    redirect_uri VARCHAR(500) NOT NULL,
    scope VARCHAR(500),
    state VARCHAR(255),
    status TINYINT DEFAULT 1,
    expire_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    used_time TIMESTAMP,
    CONSTRAINT uk_oauth_code UNIQUE (code),
    CONSTRAINT fk_oauth_code_account FOREIGN KEY (user_id) REFERENCES account(id)
);
CREATE INDEX idx_oauth_code_client_user ON oauth_code(client_key, user_id);

CREATE TABLE third_party_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    third_party_id VARCHAR(100) NOT NULL,
    third_party_username VARCHAR(100),
    third_party_email VARCHAR(100),
    third_party_avatar VARCHAR(255),
    access_token VARCHAR(500),
    refresh_token VARCHAR(500),
    expires_at TIMESTAMP,
    bind_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_time TIMESTAMP,
    status TINYINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT DEFAULT 0,
    CONSTRAINT uk_third_party UNIQUE (provider, third_party_id),
    CONSTRAINT fk_third_party_account FOREIGN KEY (user_id) REFERENCES account(id)
);

CREATE TABLE user_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    username VARCHAR(100),
    client_ip VARCHAR(50),
    user_agent VARCHAR(1000),
    location VARCHAR(200),
    device_fingerprint VARCHAR(200),
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_access_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expire_time TIMESTAMP,
    status TINYINT DEFAULT 1,
    logout_reason VARCHAR(100),
    logout_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_session UNIQUE (session_id),
    CONSTRAINT fk_user_session_account FOREIGN KEY (user_id) REFERENCES account(id)
);

CREATE TABLE token_monitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id VARCHAR(100) NOT NULL,
    token_type VARCHAR(50),
    user_id BIGINT,
    username VARCHAR(100),
    client_id VARCHAR(100),
    event_type VARCHAR(50) NOT NULL,
    event_desc CLOB,
    client_ip VARCHAR(50),
    user_agent VARCHAR(500),
    request_url VARCHAR(500),
    request_method VARCHAR(10),
    location VARCHAR(200),
    device_fingerprint VARCHAR(200),
    risk_score INT DEFAULT 0,
    risk_reason CLOB,
    is_abnormal TINYINT DEFAULT 0,
    abnormal_type VARCHAR(50),
    handle_status VARCHAR(20),
    handle_result CLOB,
    handle_remark CLOB,
    handler_id BIGINT,
    handle_time TIMESTAMP,
    token_create_time TIMESTAMP,
    token_expire_time TIMESTAMP,
    session_id VARCHAR(100),
    extra_info CLOB,
    event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_token_monitor_token ON token_monitor(token_id);
CREATE INDEX idx_token_monitor_user ON token_monitor(user_id);

CREATE TABLE traffic_monitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(100),
    client_ip VARCHAR(50),
    user_id BIGINT,
    request_path VARCHAR(500),
    request_method VARCHAR(10),
    user_agent VARCHAR(1000),
    response_status INT,
    response_time BIGINT,
    request_size BIGINT,
    response_size BIGINT,
    is_abnormal BOOLEAN,
    abnormal_type VARCHAR(100),
    risk_score INT,
    block_status INT,
    block_reason VARCHAR(500),
    geo_location VARCHAR(200),
    device_fingerprint VARCHAR(200),
    request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
