import {
  Activity,
  ChevronLeft,
  ChevronRight,
  Database,
  FileSearch,
  FileText,
  Folder,
  Home,
  LogOut,
  Megaphone,
  MessageSquare,
  Moon,
  Settings,
  Share2,
  Shield,
  Sun,
  Ticket,
  Upload,
  Users,
} from "@lucide/svelte";

export const appIconMap = {
  home: Home,
  folder: Folder,
  share: Share2,
  upload: Upload,
  users: Users,
  message: MessageSquare,
  megaphone: Megaphone,
  ticket: Ticket,
  settings: Settings,
  database: Database,
  "file-text": FileText,
  "file-search": FileSearch,
  activity: Activity,
  shield: Shield,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
} as const;

export type AppIconName = keyof typeof appIconMap;
