"""Lock OTLP defaults and operator overrides across shell and image entrypoints."""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[3]
MODULES = ("platform-backend", "platform-fisco", "platform-storage")
PROTOCOL = "OTEL_EXPORTER_OTLP_PROTOCOL"
ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"


class OtlpConfigurationTest(unittest.TestCase):
    """Exercise generated options and actual image entrypoint commands without Java."""

    def setUp(self) -> None:
        """Create an isolated release so tests never source a developer's secrets."""
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        for directory in ("bin", "agent/otel", "fake"):
            (self.root / directory).mkdir(parents=True)
        shutil.copyfile(ROOT / "scripts/env.sh", self.root / "bin/env.sh")
        (self.root / "agent/otel/opentelemetry-javaagent.jar").touch()
        self.env = {"PATH": f"{self.root / 'fake'}:{os.environ['PATH']}",
                    "RECORD_PLATFORM_SKIP_DOTENV": "true"}
        fake_java = self.root / "fake/java"
        fake_java.write_text('''#!/usr/bin/env python3
import json, os, sys
print(json.dumps({"args": sys.argv[1:], "env": {
    key: value for key, value in os.environ.items() if key.startswith("OTEL_")
}}))
''')
        fake_java.chmod(0o755)

    def tearDown(self) -> None:
        """Remove only temporary fixtures after every command has exited."""
        self.temp.cleanup()

    def script(self, overrides: dict[str, str] | None = None,
               service: str = "record-platform-storage") -> dict:
        """Execute the options generated by env.sh through the controlled Java boundary."""
        result = subprocess.run(
            ["bash", "-c", 'source "$1" >/dev/null; opts=$(get_otel_opts "$2"); java $opts',
             "test", str(self.root / "bin/env.sh"), service],
            env={**self.env, **(overrides or {})}, text=True, capture_output=True,
            check=True, timeout=10,
        )
        return json.loads(result.stdout)

    def image(self, module: str, overrides: dict[str, str] | None = None) -> dict:
        """Run the checked-in image entrypoint with Docker ENV plus runtime overrides."""
        dockerfile = (ROOT / module / "Dockerfile").read_text()
        image_env = dict(re.findall(r"^ENV ([A-Z_]+)=(\S+)$", dockerfile, re.MULTILINE))
        entrypoint = dockerfile.split("ENTRYPOINT ", 1)[1].replace("\\\n", "")
        command = json.loads(entrypoint)
        result = subprocess.run(
            command, env={**self.env, **image_env, **(overrides or {})},
            text=True, capture_output=True, check=True, timeout=10,
        )
        return json.loads(result.stdout)

    def assert_pair(self, result: dict, protocol: str, endpoint: str, *, image: bool = False) -> None:
        """Require the effective environment and generated JVM settings to agree."""
        self.assertEqual(protocol, result["env"][PROTOCOL])
        self.assertEqual(endpoint, result["env"][ENDPOINT])
        options = [arg for arg in result["args"] if arg.startswith("-Dotel.exporter.otlp.")]
        if image:
            self.assertEqual([], options, "Image JVM constants must not override Docker environment")
        else:
            self.assertCountEqual([
                f"-Dotel.exporter.otlp.protocol={protocol}",
                f"-Dotel.exporter.otlp.endpoint={endpoint}",
            ], options)

    def test_script_defaults_match_grpc_listener(self) -> None:
        """Default options explicitly select gRPC rather than Agent 2.x's HTTP default."""
        result = self.script()
        self.assert_pair(result, "grpc", "http://localhost:4317")
        self.assertIn("-Dotel.service.name=record-platform-storage", result["args"])
        self.assertTrue(any(arg.startswith("-javaagent:") for arg in result["args"]))

    def test_micrometer_bridge_defaults_only_for_providers(self) -> None:
        """Providers bridge application meters; backend retains its Actuator-only default."""
        key = "OTEL_INSTRUMENTATION_MICROMETER_ENABLED"
        for module, service, default in (
            ("platform-storage", "record-platform-storage", "true"),
            ("platform-fisco", "record-platform-fisco", "true"),
            ("platform-backend", "record-platform-web", "false"),
        ):
            for override in (None, "true", "false"):
                with self.subTest(module=module, override=override):
                    env = {} if override is None else {key: override}
                    expected = default if override is None else override
                    self.assertIn(f"-Dotel.instrumentation.micrometer.enabled={expected}",
                                  self.script(env, service)["args"])
                    self.assertEqual(expected, self.image(module, env)["env"].get(key, "false"))

    def test_provider_default_does_not_leak_to_next_service(self) -> None:
        """Calling options for a provider then backend keeps the backend bridge disabled."""
        result = subprocess.run(
            ["bash", "-c", 'source "$1" >/dev/null; get_otel_opts record-platform-fisco >/dev/null; '
             'opts=$(get_otel_opts record-platform-web); java $opts',
             "test", str(self.root / "bin/env.sh")],
            env=self.env, text=True, capture_output=True, check=True, timeout=10,
        )
        self.assertIn("-Dotel.instrumentation.micrometer.enabled=false",
                      json.loads(result.stdout)["args"])

    def test_script_preserves_explicit_protocol_and_endpoint_pairs(self) -> None:
        """Honor explicit gRPC, HTTP/protobuf and custom TLS endpoints verbatim."""
        for protocol, endpoint in (
            ("grpc", "http://collector.example:4317"),
            ("http/protobuf", "http://collector.example:4318"),
            ("grpc", "https://collector.example:9443/custom"),
            ("http/protobuf", "https://collector.example:8443/otel"),
        ):
            with self.subTest(protocol=protocol, endpoint=endpoint):
                self.assert_pair(self.script({PROTOCOL: protocol, ENDPOINT: endpoint}), protocol, endpoint)

    def test_endpoint_override_does_not_infer_protocol_from_port(self) -> None:
        """Changing a port never silently changes the configured transport."""
        self.assert_pair(self.script({ENDPOINT: "https://collector.example:4318"}),
                         "grpc", "https://collector.example:4318")
        self.assert_pair(self.script({PROTOCOL: "http/protobuf"}),
                         "http/protobuf", "http://localhost:4317")

    def test_dotenv_effective_values_generate_matching_options(self) -> None:
        """Values sourced from the deployment env file also drive the JVM options."""
        (self.root / ".env").write_text(
            "OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf\n"
            "OTEL_EXPORTER_OTLP_ENDPOINT=https://collector.example:8443\n"
        )
        self.assert_pair(self.script({"RECORD_PLATFORM_SKIP_DOTENV": "false"}),
                         "http/protobuf", "https://collector.example:8443")

    def test_script_keeps_signal_specific_configuration(self) -> None:
        """Do not synthesize signal JVM properties that override operator environment."""
        overrides = {}
        for signal in ("TRACES", "METRICS", "LOGS"):
            overrides[f"OTEL_EXPORTER_OTLP_{signal}_PROTOCOL"] = "http/protobuf"
            overrides[f"OTEL_EXPORTER_OTLP_{signal}_ENDPOINT"] = f"https://collector.example/v1/{signal.lower()}"
        result = self.script(overrides)
        self.assert_pair(result, "grpc", "http://localhost:4317")
        for key, value in overrides.items():
            self.assertEqual(value, result["env"][key])

    def test_all_image_defaults_and_overrides_match_contract(self) -> None:
        """Every image passes the effective Docker environment to its unchanged entrypoint."""
        for module in MODULES:
            for overrides in ({}, {PROTOCOL: "grpc", ENDPOINT: "https://collector.example:9443"},
                              {PROTOCOL: "http/protobuf", ENDPOINT: "http://collector.example:4318"}):
                with self.subTest(module=module, overrides=overrides):
                    result = self.image(module, overrides)
                    self.assert_pair(result, overrides.get(PROTOCOL, "grpc"),
                                     overrides.get(ENDPOINT, "http://otel-collector:4317"), image=True)
                    self.assertIn("-javaagent:/opt/otel/opentelemetry-javaagent.jar", result["args"])

    def test_images_preserve_signal_overrides_and_agent_disable(self) -> None:
        """Transport defaults do not force the agent on or clobber per-signal settings."""
        overrides = {"OTEL_JAVAAGENT_ENABLED": "false"}
        for signal in ("TRACES", "METRICS", "LOGS"):
            overrides[f"OTEL_EXPORTER_OTLP_{signal}_PROTOCOL"] = "http/protobuf"
            overrides[f"OTEL_EXPORTER_OTLP_{signal}_ENDPOINT"] = f"https://collector.example/v1/{signal.lower()}"
        for module in MODULES:
            with self.subTest(module=module):
                result = self.image(module, overrides)
                self.assert_pair(result, "grpc", "http://otel-collector:4317", image=True)
                self.assertFalse(any(arg.startswith("-javaagent:") for arg in result["args"]))
                for key, value in overrides.items():
                    self.assertEqual(value, result["env"][key])

    def test_template_and_bilingual_docs_state_matching_defaults(self) -> None:
        """Keep startup defaults and operator-facing protocol guidance synchronized."""
        template = (ROOT / ".env.example").read_text()
        self.assertRegex(template, r"(?m)^OTEL_EXPORTER_OTLP_PROTOCOL=grpc$")
        self.assertRegex(template, r"(?m)^OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317$")
        for language in ("en", "zh"):
            doc = (ROOT / f"docs/{language}/deployment/monitoring.md").read_text()
            self.assertIn("| `OTEL_EXPORTER_OTLP_PROTOCOL` | `grpc` |", doc)
            self.assertIn("http://otel-collector:4317", doc)
            self.assertIn("OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf", doc)
            self.assertIn("OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318", doc)
            self.assertIn("OTEL_EXPORTER_OTLP_TRACES_PROTOCOL", doc)
            self.assertIn("/v1/metrics", doc)


if __name__ == "__main__":
    unittest.main()
